generate:
  - client
  - types
filter:
  operations:
    - buildUploads_createInstance # Start uploading the build
    - buildUploadFiles_createInstance # Upload binary
    - buildUploadFiles_updateInstance # Finish the upload
    - buildUploads_getInstance

    - buildBetaDetails_build_getToOneRelated # Get TF build details
    - builds_getCollection # Get app builds filtered with appId
    - builds_getInstance # Get build by ID
    - builds_appEncryptionDeclaration_getToOneRelationship # GET /v1/builds/{id}/relationships/appEncryptionDeclaration
    - builds_appEncryptionDeclaration_updateToOneRelationship # PATCH /v1/builds/{id}/relationships/appEncryptionDeclaration
    - builds_betaGroups_createToManyRelationship # POST /v1/builds/{id}/relationships/betaGroups
    - builds_betaBuildLocalizations_getToManyRelated # GET /v1/builds/{id}/betaBuildLocalizations

    - betaAppReviewSubmissions_createInstance # POST /v1/betaAppReviewSubmissions

    - betaBuildLocalizations_createInstance # POST /v1/betaBuildLocalizations
    - betaBuildLocalizations_getInstance # GET /v1/betaBuildLocalizations/{id}
    - betaBuildLocalizations_updateInstance # PATCH /v1/betaBuildLocalizations/{id}

    - betaGroups_getCollection # GET /v1/betaGroups
    - betaGroups_getInstance # GET /v1/betaGroups/{id}
    - betaGroups_builds_getToManyRelationship # GET /v1/betaGroups/{id}/relationships/builds
    - betaGroups_builds_createToManyRelationship # POST /v1/betaGroups/{id}/relationships/builds
    - betaGroups_builds_deleteToManyRelationship # DELETE /v1/betaGroups/{id}/relationships/builds

    - buildBetaNotifications_createInstance # POST /v1/buildBetaNotifications
    - buildBundles_buildBundleFileSizes_getToManyRelated # GET /v1/buildBundles/{id}/buildBundleFileSizes

    - userInvitations_createInstance # POST /v1/userInvitations
    - betaTesters_createInstance # POST /v1/betaTesters
    - betaTesters_getCollection # GET /v1/betaTesters
    - betaTesterInvitations_createInstance # POST /v1/betaTesterInvitations
    - betaTesters_betaGroups_createToManyRelationship # POST /v1/betaTesters/{id}/relationships/betaGroups
    - betaTesters_betaGroups_deleteToManyRelationship # DELETE /v1/betaTesters/{id}/relationships/betaGroups
namingStrategy: idiomatic

# Run from root when changed:
# ./Scripts/update_api.sh TestflightAPI
